### ISSUE TITLE
Monitor smoothie charts require UT data but timeflux uses local time

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux_ui#10]
Timeflux generally uses now() which returns local time. 

But if my source data is timestamped at with Pandas timezone-naive timestamps in my local timezone (BST = UT + 1) then my smoothie charts are blank (although they are validly scaled so the data is reaching the web app).

I believe this is because smoothie expects timestamps to be in UT timezone. In its docs in the examples it uses javascipt's getTime() which returns UT.

If using local time is the timeflux convention, then we need to convert to UT in either ui.py or in the monitor.js

**Comment by mesca** [comment]
It is assumed that all timestamps are UTC. On my machine, `now()` returns a UTC datetime:
```
from timeflux.helpers.clock import now
now()
```

Do you encounter a different behavior?
