### ISSUE TITLE
Naming target same and then changing it later causes wrong UI output

### ISSUE THREAD

**Issue by ksslng** [timeflux/timeflux_ui#6]
In the [hello sinus example](https://github.com/timeflux/hackathon/blob/master/graphs/hello_sinus/hello_sinus_solution_part4.yaml#L84), first changing the target of the first two to the UI the same name. Starting the graph and opening the UI. Change the names to the correct one (two new different names in my case), stopping timeflux and starting it immediately, while keeping the UI open, will lead to, that in the ouput graphs, the two new streams have the same output value.
I could also reproduce it, when closing the UI and timeflux for awhile.

**Comment by mesca** [comment]
The browser session is bound to a Timeflux instance. So you need to refresh the page if you restart Timeflux and your streams names have changed.
