### ISSUE TITLE
Data dissappearing out of range on a monitor chart

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux_ui#7]
In a few different circumstances, I've found data to dissappear from view on a monitor smoothie chart, because it's outside the range of the y axis. There's no open issue for smoothie.js that looks like this, so it may not be an upstream bug.

In theory this shouldn't happen, and I've wondered if it's because of my code doing something unusual like overwriting the past history by supplying an output dataframe whose index timestamps overlap with previous dataframes. But as far as I can see my code is NOT doing this, so I'm not sure that's the problem.

I have found that commenting out the     
```
//maxValueScale: 1.2,
//minValueScale: 1.2,
```
in ui.js fixes the problem. 

I've no idea what the root cause is here, and can't provide a reproducible example. But I'm opening this issue to pool knowledge on this.

**Comment by mesca** [comment]
``maxValueScale`` and ``minValueScale`` are passed directly to smoothie, so I am not sure what I can do to fix this. If you have a HDF5 file that I could replay, that would be very helpful.
